apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.mongo.name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
