apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-app-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
    - port: "5000"
