apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
      volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
    - name: dind
      image: drpsychick/dind-buildx-helm:latest
      alwaysPull: true
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        - name: DOCKER_CGROUPS
          value: "true"
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: "/home/jenkins/agent"
          name: "workspace-volume"
  volumes:
    - emptyDir: {}
      name: dind-storage
    - emptyDir: {}
      name: workspace-volume
