flask:
  replicaCount: 3
  image: saddff/flask_app:0.6amd64
  namespace: flask-app
  mongouri: mongodb://mongo:27017/dinner_suggestions

mongo:
  image: mongo:latest
  name: mongo
  mongodb_login: root
  mongodb_password: example
